language: php

php:
  - 5.6
  - 7.0
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.1 WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
